Assignments/pete/capstone/final_build2/tracker/urls.py
from django.urls import path

from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.tracker, name='tracker'),
    path('add-day/', views.add_day, name='add_day'),
    path('day/<int:pk>/', views.get_day, name='get_day'),# change views.get_day <-> views.get_day_charts
    path('entry/<int:pk>/', views.entry, name='entry'),
    path('add-entry/<int:pk>/', views.add_entry, name='add_entry'),
    path('saved-entry/<int:pk>/', views.saved_entry, name='saved_entry'),
    path('day-canvas/<int:pk>/', views.day_canvas, name='day_canvas'),#test for self-made canvas graph in day
    path('nutritionix/<int:pk>/', views.nutritionix, name='nutritionix'),
]

Assignments/pete/capstone/final_build2/tracker/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from .models import *

"""
RENDER VIEWS
"""

@login_required
def tracker(request):
    days = DiaryDay.objects.filter(user=request.user).order_by('-date')
    # days = DiaryDay.objects.order_by('-date')
    days_json = [day.date for day in days]
    return render(request, 'tracker/tracker.html', {'days': days, 'days_json': days_json})

@login_required
def get_day(request, pk):
    day = DiaryDay.objects.get(pk=pk)
    totals = day.total()
    offset = day.offset()
    over_under = day.over_under()
    return render(request, 'tracker/day.html', {'day': day, 'macros': day.macros(), 'totals': totals, 'offset': offset, 'over_under': over_under, 'user': request.user})
    
@login_required
def get_day_charts(request, pk):
    day = DiaryDay.objects.get(pk=pk)
    totals = day.total()
    offset = day.offset()
    over_under = day.over_under()
    return render(request, 'tracker/day-charts.html', {'day': day, 'macros': day.macros(), 'totals': totals, 'offset': offset, 'over_under': over_under, 'user': request.user})
    
@login_required
def entry(request, pk):
    day = DiaryDay.objects.get(pk=pk)
    return render(request, 'tracker/entry.html', {'day': day, 'general_meals': Meal.objects.filter(general=True)})

@login_required
def day_canvas(request, pk):
    day = DiaryDay.objects.get(pk=pk)
    totals = day.total()
    offset = day.offset()
    over_under = day.over_under()
    return render(request, 'tracker/day-canvas.html', {'day': day, 'macros': day.macros(), 'totals': totals, 'offset': offset, 'over_under': over_under, 'user': request.user})
    return HttpResponse('canvas')

@login_required
def nutritionix(request, pk):
    day = DiaryDay.objects.get(pk=pk)
    return render(request, 'tracker/nutritionix.html')

"""
REDIRECT VIEWS
"""

@login_required
def add_day(request):
    training = request.POST['day-type'] == 'train'
    date = request.POST['date']
    day = DiaryDay(user=request.user, training=training, date=date)
    day.save()
    return HttpResponseRedirect(reverse('tracker:get_day', kwargs={'pk': day.pk}))
    # return render(request, 'tracker/day.html', {'day': day, 'macros': day.macros()})

@login_required
def add_entry(request, pk):

    day = DiaryDay.objects.get(pk=pk)
    name = request.POST['name']
    kcal = request.POST['kcal']
    fat = request.POST['fat']
    carb = request.POST['carb']
    protein = request.POST['protein']
    meal = Meal(name=name, kcal=kcal, fat=fat, carb=carb, protein=protein)
    meal.save()

    if request.POST.get('save', None):
        meal.user.add(request.user)

    DiaryEntry(meal=meal, date=day).save()
    return HttpResponseRedirect(reverse('tracker:get_day', kwargs={'pk': day.pk}))

@login_required
def saved_entry(request, pk):

    day = DiaryDay.objects.get(pk=pk)
    meal = Meal.objects.get(pk=request.POST['meal'])
    DiaryEntry(meal=meal, date=day).save()
    return HttpResponseRedirect(reverse('tracker:get_day', kwargs={'pk': day.pk}))

Assignments/pete/capstone/final_build2/tracker/templates/tracker/day.html
{% extends 'home/base.html' %}
{% load static %}

{% block head %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'tracker/css/day.css' %}">
    <script src="{% static 'tracker/js/day.js' %}" defer></script>
    {% block entry_head %}
    {% endblock %}
</head>
{% endblock %}

{% block main %}
<main class="day">
    <header class="big">{{ day.date }} || {% if day.training %}Training Day{% else %}Rest Day{% endif %}</header>
    <div id="outer-day">

        <div class="middle-day">
            <header class="small">Goals</header>
            <div class="goal-div"><span>Calories:</span><span>{{ macros.kcal }} kcal</span></div>
            <div class="goal-div"><span>Fat:</span><span>{{ macros.fat }} g</span></div>
            <div class="goal-div"><span>Carbohydrates:</span><span>{{ macros.carb }} g</span></div>
            <div class="goal-div"><span>Protein:</span><span>{{ macros.protein }} g</span></div>
        </div>

        
        <div class="middle-day">
            <header class="small">Progress</header>
            <div class="prog-div">
                <span>Calories: {{ totals.kcal }}/{{ macros.kcal }} kcal</span>
                <span>You are {{ over_under.kcal }} on Kcal</span>
            </div>
            
            <div class="prog-div">
                <span>Fat: {{ totals.fat }}/{{ macros.fat }} g</span>
                <span>You are {{ over_under.fat }} on Fat</span>
            </div>

            <div class="prog-div">
                <span>Carbs: {{ totals.carb }}/{{ macros.carb }} g</span>
                <span>You are {{ over_under.carb }} on Carbs</span>
            </div>

            <div class="prog-div">
                <span>Protein {{ totals.protein }}/{{ macros.protein }} g</span>
                <span>You are {{ over_under.protein }} on Protein</span>
            </div>
        </div>
        
        <div id="outer-entry">
            <header class="small">Entries:</header>
            <div id="inner-entry">
                {% for entry in day.diary_entry.all %}
                <div class="entry">
                    <div class="name">{{ entry.meal.name }}</div>
                    <div>{{ entry.meal.kcal }} Kcal</div>
                    <div>{{ entry.meal.fat }} g Fat</div>
                    <div>{{ entry.meal.carb }} g Carbs</div>
                    <div>{{ entry.meal.protein }} g Protein</div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
    <a href="{% url 'tracker:entry' pk=day.pk %}"><button>Add Entry!</button></a>
    
{% block entry_main %}
{% endblock %}
</main>
{% endblock %}