Assignments/pete/capstone/prototype2/macro_tracker/mac/urls.py
from django.urls import path

from . import views

app_name = 'mac'

urlpatterns = [
    path('', views.index, name='index'),
    path('calc/', views.calc, name='calc'),
    path('calc-macros/', views.calc_macros, name='calc_macros'),
    # path('macros/')
]

Assignments/pete/capstone/prototype2/macro_tracker/mac_trak_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mac.urls')),
    path('user/', include('user.urls')),
    path('trak/', include('trak.urls')),
]

Assignments/pete/capstone/prototype2/macro_tracker/trak/urls.py
from django.urls import path

from . import views

app_name = 'trak'

urlpatterns = [
    path('', views.index, name='index'),
    path('diary/', views.diary, name='diary'),
    path('update-diary/', views.update_diary, name='update_diary'),
]

Assignments/pete/capstone/prototype2/macro_tracker/trak/models.py
from django.db import models
from django.contrib.auth.models import User
from user.models import UserProfile

class Meal(models.Model):
    name = models.CharField(max_length=140)#name of food
    kcal = models.IntegerField()#kilocalories
    fat = models.IntegerField()#g of fat
    carbs = models.IntegerField()#g of carbs
    protein = models.IntegerField()#g of protein
    def __str__(self):
        return f"{self.name} ({self.kcal}/{self.fat}/{self.carbs}/{self.protein})"

class DiaryDay(models.Model):
    date = models.DateField(auto_now=True)#date of each diary
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='diary_day')
    training = models.BooleanField()#true for training day false for rest day
    def total(self):
        total_dict = {'kcal': 0, 'fat': 0, 'carbs': 0, 'protein': 0}
        for entry in self.diary_entry.all():
            for key in total_dict.keys():
                total_dict[key] += getattr(entry.meal, key)
        return total_dict
    def __str__(self):
        return str(self.date)

class DiaryEntry(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.PROTECT)#each entry is linked to a saved meal
    date = models.ForeignKey(DiaryDay, on_delete=models.PROTECT, related_name='diary_entry')
    time = models.TimeField(auto_now=True)#the time of the entry
    def __str__(self):
        return f"{self.date} {self.time} {self.meal}"

Assignments/pete/capstone/prototype2/macro_tracker/trak/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect

from .models import Meal, DiaryDay, DiaryEntry

@login_required
def index(request):
    return render(request, 'trak/index.html', {'macros': request.user.macros})

@login_required
def diary(request):
    return render(request, 'trak/diary.html', {'meals': Meal.objects.all()})

@login_required
def update_diary(request):
    if not request.POST['new-day']:
        return HttpResponse('choose day')

    '''
    if request.POST['day-type'] == 'train':
        training = True
    else:
        training = False
    shorter version below
    '''

    training = request.POST['day-type'] == 'train'
    day = DiaryDay(user=request.user, training=training)
    day.save()

    meal = Meal.objects.get(pk=request.POST['meal'])
    entry = DiaryEntry(meal=meal, date=day)
    entry.save()

    entries = day.diary_entry.all()
    totals = day.total()

    return render(request, 'trak/day.html', {'day': day, 'entries': entries, 'totals': totals, 'user': request.user})

Assignments/pete/capstone/prototype2/macro_tracker/trak/templates/trak/day-list.html
<h1>Your Days:</h1>
<ul>
    <li>
        <a href="{% url 'trak:new_day' %}">
            <button>New Day</button>
        </a>
    </li>
{% for day in days %}
    <li>
        <!-- DAY 2!!! -->
        <a href="{% url 'trak:day2' pk=day.pk %}">
        <!-- DAY 2!!! -->
            <button>{{day.date}}: {{day.type}}</button>
        </a>
    </li>
{% endfor %}
</ul>

Assignments/pete/capstone/prototype2/macro_tracker/trak/templates/trak/day.html
<h1>\/\/ |-| /-\ -|- __ /-\ |\| __ E /-\ -|- Y __ |} /-\ Y</h1>
<h2>{{ day.date }}</h2>
<!-- Goal -->
<h3>Goal</h3>
{% if day.training %}
<h4>Training Day Macros</h4>
<ul>
    <li>{{ user.macros.train_kcal }} kcal</li>
    <li>{{ user.macros.train_fat }} g</li>
    <li>{{ user.macros.train_carb }} g</li>
    <li>{{ user.macros.protein }} g</li>
</ul>
{% else %}
<h4>Rest Day Macros</h4>
<ul>
    <li>{{ user.macros.rest_kcal }} kcal</li>
    <li>{{ user.macros.rest_fat }} g</li>
    <li>{{ user.macros.rest_carb }} g</li>
    <li>{{ user.macros.protein }} g</li>
</ul>
{% endif %}
<!-- Entries -->
<h3>Entries</h3>
<ul>
{% for entry in entries %}
    <li>{{ entry.meal.name }}
        <ul>
            <li>{{ entry.meal.kcal }} kcal</li>
            <li>{{ entry.meal.fat }} g</li>
            <li>{{ entry.meal.carbs }} g</li>
            <li>{{ entry.meal.protein }} g</li>
        </ul>
    </li>
{% endfor %}
</ul>
<!-- Total -->
<h3>Total</h3>
<ul>
    <li>{{ totals.kcal }} kcal</li>
    <li>{{ totals.fat }} g</li>
    <li>{{ totals.carbs }} g</li>
    <li>{{ totals.protein }} g</li>
</ul>

Assignments/pete/capstone/prototype2/macro_tracker/trak/templates/trak/diary.html
<h1>|-| 3 |_ |_ 0 ___ F R | 3 |\| D 5</h1>

<form action="{% url 'trak:update_diary' %}" method="POST">
{% csrf_token %}
    <ul>
        <li>New Day?        
            <input name="new-day" type="radio" value="True" checked>Yes
            <input name="new-day" type="radio" value="">No
        </li>
        <li>Day Type?
            <input name="day-type" type="radio" value="train" checked>Training
            <input name="day-type" type="radio" value="rest">Rest
        </li>
        <li>
            <select name="meal">
            {% for meal in meals %}
                <option value="{{meal.pk}}">{{ meal.name }}</option>
            {% endfor %}
            </select>
        </li>
    </ul>
    <button type="submit">Oh yeah let's add it to the tracker!</button>
</form>

Assignments/pete/capstone/prototype2/macro_tracker/trak/templates/trak/diary2.html
<h1>|-| 3 |_ |_ 0 ___ F R | 3 |\| D 5</h1>

<form action="{% url 'trak:update_diary2' %}" method="POST">
{% csrf_token %}
    <ul>
        <li>Select Day:
            <select name="day">
            {% for day in days%}
                <option value="{{day.pk}}">{{ day.date }}</option>
                <option value="new">New Day</option>
            </select>
        </li>
        <li>Day Type?
            <input name="day-type" type="radio" value="train" checked>Training
            <input name="day-type" type="radio" value="rest">Rest
        </li>
        <li>
            <select name="meal">
            {% for meal in meals %}
                <option value="{{meal.pk}}">{{ meal.name }}</option>
            {% endfor %}
            </select>
        </li>
    </ul>
    <button type="submit">Oh yeah let's add it to the tracker!</button>
</form>

Assignments/pete/capstone/prototype2/macro_tracker/trak/templates/trak/index.html
<h1>Your /\/\ /-\ {ros</h1>
<h2>\/\/ |-| /-\ T   /-\   |-|ealth!</h2>
<ul>
    <li>
        <h4>Training Day:</h4>
        <ul>
            <li>Calories: {{ macros.train_kcal }}</li>
            <li>Fat: {{ macros.train_fat }}g</li>
            <li>Carbohydrates: {{ macros.train_carb }}g</li>
            <li>Protein: {{ macros.protein }}g</li>
        </ul>
    </li>
    <li>
        <h4>Rest Day:</h4>
        <ul>
            <li>Calories: {{ macros.rest_kcal }}</li>
            <li>Fat: {{ macros.rest_fat }}g</li>
            <li>Carbohydrates: {{ macros.rest_carb }}g</li>
            <li>Protein: {{ macros.protein }}g</li>
        </ul>
    </li>
</ul>


<h2>So them's that's and they's your's macro's</h2>
<h3>Now let's get around to tracking your meals:</h3>

<a href="{% url 'trak:diary' %}"><button>Now that's what I'm talkin' about!</button></a>

Assignments/pete/capstone/prototype2/macro_tracker/trak/templates/trak/new-day.html
<h1>Add a new day</h1>

<form action="{% url 'trak:add_new_day' %}" method="POST">
{$ csrf_token %}
    <input type="date" name="date">
    <button type="submit">Go!</button>
</form>